### ISSUE TITLE
Add instrumentation hooks

### ISSUE THREAD

**Issue by dasch** [zendesk/ruby-kafka#40]
There are several moving parts in the producer, and it will be important to measure:

- [x] The size of local buffers, both in number of pending messages _and_ relative to the max buffer size.
- [x] Latency and throughput of individual API requests/responses.
- [x] Latency and throughput of high-level operations such as produce operations: #81.
- [x] Errors, timeouts, and retries.
- [x] Throughput and latency for individual topics/partitions: #60.
- [x] Per-message delivery delay – time spent in the buffer: #137.
- [x] Producer delivery rate – time between deliveries.

Exactly how the hooks will work also needs to be decided. One option would be to simply use ActiveSupport::Notifications if it's available, or an API compatible null sink if it's not. An alternative is a custom callback system, but that feels a bit like overkill to me.
